//------------------------------------------------------------------------------
//  input/nkeycodes.cc
//  (C) 2006 RadonLabs GmbH
//------------------------------------------------------------------------------
#include "input/nkeycodes.h"

#ifndef __XBxX__
/*
    -24-Aug-05    kims    Fixed the bug #128, Added additional key mapping.
                          Thanks Megan Fox and Chris Tencati for the pointing out this.
*/
nStrToKey key_remaptable[] = {
    { "bs",         N_KEY_BACK, },
    { "tab",        N_KEY_TAB, },
    { "return",     N_KEY_RETURN, },
    { "shift",      N_KEY_SHIFT, },
    { "ctrl",       N_KEY_CONTROL, },
    { "menu",       N_KEY_MENU, },
    { "pause",      N_KEY_PAUSE, },
    { "capital",    N_KEY_CAPITAL, },
    { "esc",        N_KEY_ESCAPE, },
    { "space",      N_KEY_SPACE, },
    { "prior",      N_KEY_PRIOR, },
    { "next",       N_KEY_NEXT, },
    { "end",        N_KEY_END, },
    { "home",       N_KEY_HOME, },
    { "left",       N_KEY_LEFT, },
    { "up",         N_KEY_UP, },
    { "right",      N_KEY_RIGHT, },
    { "down",       N_KEY_DOWN, },
    { "select",     N_KEY_SELECT, },
    { "print",      N_KEY_PRINT, },
    { "exec",       N_KEY_EXECUTE, },
    { "snap",       N_KEY_SNAPSHOT, },
    { "insert",     N_KEY_INSERT, },
    { "delete",     N_KEY_DELETE, },
    { "help",       N_KEY_HELP, },
    { "1",          N_KEY_1, },
    { "2",          N_KEY_2, },
    { "3",          N_KEY_3, },
    { "4",          N_KEY_4, },
    { "5",          N_KEY_5, },
    { "6",          N_KEY_6, },
    { "7",          N_KEY_7, },
    { "8",          N_KEY_8, },
    { "9",          N_KEY_9, },
    { "0",          N_KEY_0, },
    { "a",          N_KEY_A, },
    { "b",          N_KEY_B, },
    { "c",          N_KEY_C, },
    { "d",          N_KEY_D, },
    { "e",          N_KEY_E, },
    { "f",          N_KEY_F, },
    { "g",          N_KEY_G, },
    { "h",          N_KEY_H, },
    { "i",          N_KEY_I, },
    { "j",          N_KEY_J, },
    { "k",          N_KEY_K, },
    { "l",          N_KEY_L, },
    { "m",          N_KEY_M, },
    { "n",          N_KEY_N, },
    { "o",          N_KEY_O, },
    { "p",          N_KEY_P, },
    { "q",          N_KEY_Q, },
    { "r",          N_KEY_R, },
    { "s",          N_KEY_S, },
    { "t",          N_KEY_T, },
    { "u",          N_KEY_U, },
    { "v",          N_KEY_V, },
    { "w",          N_KEY_W, },
    { "x",          N_KEY_X, },
    { "y",          N_KEY_Y, },
    { "z",          N_KEY_Z, },
    { "lwin",       N_KEY_LWIN, },
    { "rwin",       N_KEY_RWIN, },
    { "apps",       N_KEY_APPS, },
    { "num0",       N_KEY_NUMPAD0, },
    { "num1",       N_KEY_NUMPAD1, },
    { "num2",       N_KEY_NUMPAD2, },
    { "num3",       N_KEY_NUMPAD3, },
    { "num4",       N_KEY_NUMPAD4, },
    { "num5",       N_KEY_NUMPAD5, },
    { "num6",       N_KEY_NUMPAD6, },
    { "num7",       N_KEY_NUMPAD7, },
    { "num8",       N_KEY_NUMPAD8, },
    { "num9",       N_KEY_NUMPAD9, },
    { "mult",       N_KEY_MULTIPLY, },
    { "plus",       N_KEY_ADD, },
    { "sep",        N_KEY_SEPARATOR, },
    { "minus",      N_KEY_SUBTRACT, },
    { "decimal",    N_KEY_DECIMAL, },
    { "divide",     N_KEY_DIVIDE, },
    { "f1",         N_KEY_F1, },
    { "f2",         N_KEY_F2, },
    { "f3",         N_KEY_F3, },
    { "f4",         N_KEY_F4, },
    { "f5",         N_KEY_F5, },
    { "f6",         N_KEY_F6, },
    { "f7",         N_KEY_F7, },
    { "f8",         N_KEY_F8, },
    { "f9",         N_KEY_F9, },
    { "f10",        N_KEY_F10, },
    { "f11",        N_KEY_F11, },
    { "f12",        N_KEY_F12, },
    { "f13",        N_KEY_F13, },
    { "f14",        N_KEY_F14, },
    { "f15",        N_KEY_F15, },
    { "f16",        N_KEY_F16, },
    { "f17",        N_KEY_F17, },
    { "f18",        N_KEY_F18, },
    { "f19",        N_KEY_F19, },
    { "f20",        N_KEY_F20, },
    { "f21",        N_KEY_F21, },
    { "f22",        N_KEY_F22, },
    { "f23",        N_KEY_F23, },
    { "f24",        N_KEY_F24, },
    { "numlock",    N_KEY_NUMLOCK, },
    { "scroll",     N_KEY_SCROLL, },
    { "semicolon",  N_KEY_SEMICOLON, },
    { "slash",      N_KEY_SLASH, },
    { "tilde",      N_KEY_TILDE, },
    { "leftbracket",N_KEY_LEFTBRACKET, },
    { "backslash",  N_KEY_BACKSLASH, },
    { "rightbracket", N_KEY_RIGHTBRACKET, },
    { "quote",        N_KEY_QUOTE, },
    { "comma",        N_KEY_COMMA, },
    { "underbar",     N_KEY_UNDERBAR, },
    { "period",       N_KEY_PERIOD,},
    { "equality",     N_KEY_EQUALITY,},
    { 0,           N_KEY_NONE },
};
#endif
