#----------------------------------------------------------------------
#  titlepage.py
#
#  (C)2005 Kim, Hyoun Woo
#----------------------------------------------------------------------
import wx
import wx.wizard as wiz
import glob, os, time
from common import *

#----------------------------------------------------------------------
#  Create Title page.
#----------------------------------------------------------------------
class TitledPage(wiz.WizardPageSimple):
    def __init__(self, parent, title):
        wiz.WizardPageSimple.__init__(self, parent)

        self.sizerA = makePageTitle(self, title)
    
        title = """
The Nebula2 Application Wizard helps you to write your own application \
which uses Nebula2 application module. 
When you startup to write your own program, the application wizard \
automatically generates module 'bld' build file, '.h' header and '.cc' \
source files. The Nebula2 Appplication Wizard provides several pages and \
each of the pages contains settings for the task.
The classes which are generated by the Nebula2 Application Wizard are derived \
from nApplication and nAppState class. \
You can change the names and settings by the controls on the each of the pages.
Enjoy!

(C)2005 Kim, Hyoun Woo"""
        self.titleTextCtrl = wx.TextCtrl(self, -1, title,
                                         size=(350, 200), 
                                         style=wx.TE_MULTILINE | wx.TE_READONLY|
                                         wx.TE_AUTO_URL|wx.TE_RICH2)
                                         

        #self.titleTextCtrl.SetInsertionPoint(0) 

        # get the current size
        points = self.titleTextCtrl.GetFont().GetPointSize()  
        fnt = wx.Font(points+1, wx.DEFAULT, wx.NORMAL, wx.BOLD, False)
        self.titleTextCtrl.SetStyle(0, 32, wx.TextAttr("BLACK", wx.NullColour, fnt))

        # Layout
        sizerB = wx.GridBagSizer(4, 1)

        sizerB.Add(self.titleTextCtrl, (0, 0), flag = wx.EXPAND)

        self.sizerA.Add(sizerB, 0, wx.ALL, 6)
        self.sizerA.Fit(self)
        self.SetSizer(self.sizerA)
    
    def validate(self):
        return True

